
title: CORE-UA 109 (Quantitative Reasoning)
short_title: CORE 109
description: "Course website for CORE-UA 109 (Quantitative Reasoning) course."

baseurl: "/core109_f19" # the subpath of your site, e.g. /blog
url: "https://joannakl.github.io/core109_f19" # the base hostname & protocol for your site, e.g. http://example.com

email_etiquette: "email_etiquette.md"

markdown: kramdown
kramdown:
  entity_output: numeric
  smart_quotes: apos,apos,quot,quot

exclude:
  - Gemfile
  - Gemfile.lock



course_number: "CORE-UA 109"
course_name: "Quantitative Reasoning"
course_section: "001"
course_semester: "Fall 2019"
course_time: "Mondays and Wednesdays 9:30AM - 10:45AM, SILV 507  <br>"

recitation_section: "002"
recitation_time:  "Thursdays 9:30AM - 10:45AM, TISC LC19 <br>"
recitation_instructor_full: "Julie Lizardo"
recitation_instructor_name: "Julie"


instructor_office_hours: "Mondays 11:30-12:30pm, Wednesdays 12:30-1:30pm, Thursdays 2:00-3:00pm
(or email me for an appointment if these hours do not work)"
instructor_office_hours_location: "423 CIWW"
recitation_office_hours: "TBD"
recitation_office_hours_location: "412 CIWW"


current_course1_title: "CSCI 102 sec. 5"
current_course1_link: "https://cs.nyu.edu/~joannakl/cs102_f19/"
current_course2_title: "CORE 109 sec. 1"
current_course2_link: "https://cs.nyu.edu/~joannakl/core109_f19/"
current_course3_title: ""
current_course3_link: ""


tutor_location: "Kimmel Center 4th floor computer lab"
tutor_schedule_link: "TBD"

midterm_exam_date: "__exam 1__: Mon, Oct. 7, __exam 2__: Mon, Nov. 11"
final_exam_date: "__Wed, Dec. 18, 8:00am-9:50am__"
final_exams_link: "http://cs.nyu.edu/dynamic/courses/exams/"

piazza_site:
github_site:

book_opt_1: "Python Learning Modules, "
book_opt_1_author: "Andrew Case, Deena Engel, and Craig Kapp "
book_opt_1_edition: ""
book_opt_1_link: "http://cs.nyu.edu/elearning/CSCI_UA_0002/"
modules: "http://cs.nyu.edu/elearning/CSCI_UA_0002"
book_opt_1_note: "**Highly recommented** - used in the Introduction to Computer Programming course."
book_opt_1_image: ""


book_opt_2: "How to Think Like a Computer Scientist, "
book_opt_2_author: "Ben Stephenson "
book_opt_2_edition: ""
book_opt_2_link: "http://openbookproject.net/thinkcs/python/english3e/"
book_opt_2_note: ""
book_opt_2_image: "resources/images/howToThinkLikeAComputerScientist.png"


book_opt_3: "The Python Workbook, "
book_opt_3_author: "Chris Mayfield, Allen Downey, "
book_opt_3_edition: ""
book_opt_3_link: ""
book_opt_3_note: "available for download for NYU students through NYU Libraries: <br>
1) login to NYU Classes using your net ID<br>
2) go to Research tab <br>
3) under NYU Libraries, use the search box to search for this title <br>"
book_opt_3_image: "resources/images/ThePythonWorkbook.jpg"


book_opt_4: "A Byte of Python, "
book_opt_4_author: "C. H. Swaroop , "
book_opt_4_edition: ""
book_opt_4_link: "http://python.swaroopch.com/"
book_opt_4_note: "free online book on programming using Python languege"
book_opt_4_image:


book_opt_5: "Python Tutor, "
book_opt_5_author: ""
book_opt_5_edition: ""
book_opt_5_link: "http://www.pythontutor.com/"
book_opt_5_note: "free online Python environment that allows code visualization
and execution line-by-line"
book_opt_5_image:



book_opt_6: "Common Sense Mathematics , "
book_opt_6_author: "Ethan Bolker and Maura Mast, "
book_opt_6_edition: ""
book_opt_6_link: "http://www.maa.org/press/books/common-sense-mathematics"
book_opt_6_note: "(OPTIONAL) good resource for some of the math topics that we are going to discuss "
book_opt_6_image: "https://www.maa.org/sites/default/files/images/pubs/books/covers/COSMcover.jpg"



book_opt_7: "Math in Society, "
book_opt_7_author: "David Lippman, "
book_opt_7_edition: ""
book_opt_7_link: "https://open.umn.edu/opentextbooks/BookDetail.aspx?bookId=98"
book_opt_7_note: "free open source book"
book_opt_7_image: "resources/images/MathInSociety.png"



book_opt_8: "Fundamentals of Mathematics, "
book_opt_8_author: "Denny Burzynski and Wade Ellis, "
book_opt_8_edition: ""
book_opt_8_link: "https://open.umn.edu/opentextbooks/BookDetail.aspx?bookId=154"
book_opt_8_note: "free open source book"
book_opt_8_image: "resources/images/FundamentalsOfMathematics.png"



book_opt_9: "Introductory Statistics, "
book_opt_9_author: "Douglas Shafer and Zhiyi Zhang, "
book_opt_9_edition: ""
book_opt_9_link: "https://open.umn.edu/opentextbooks/BookDetail.aspx?bookId=135"
book_opt_9_note: "free open source book"
book_opt_9_image: "resources/images/IntroductoryStatistics.png"



book_opt_10: "Prealgebra, "
book_opt_10_author: "Lynn Marecek and MaryAnne Anthony-Smith,  "
book_opt_10_edition: ""
book_opt_10_link: "https://open.umn.edu/opentextbooks/BookDetail.aspx?bookId=241"
book_opt_10_note: "free open source book"
book_opt_10_image: "resources/images/Prealgebra.png"


book_opt_11: "Think Python, "
book_opt_11_author: "Allen B. Downey, "
book_opt_11_edition: "2e"
book_opt_11_link: "http://greenteapress.com/wp/think-python-2e/"
book_opt_11_note: "free open source book"
book_opt_11_image: "http://greenteapress.com/thinkpython2/think_python2_medium.jpg"


book_opt_12: ", "
book_opt_12_author: ", "
book_opt_12_edition: ""
book_opt_12_link: ""
book_opt_12_note: "free open source book"
book_opt_12_image:
